/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    products: Product;
    brands: Brand;
    categories: Category;
    notes: Note;
    'gift-items': GiftItem;
    pages: Page;
    media: Media;
    orders: Order;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    products: ProductsSelect<false> | ProductsSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    notes: NotesSelect<false> | NotesSelect<true>;
    'gift-items': GiftItemsSelect<false> | GiftItemsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('ro' | 'ru' | 'en') | ('ro' | 'ru' | 'en')[];
  globals: {
    homepage: Homepage;
    settings: Setting;
    navigation: Navigation;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    settings: SettingsSelect<false> | SettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
  };
  locale: 'ro' | 'ru' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  brand: number | Brand;
  categories?: (number | Category)[] | null;
  gender?: ('female' | 'male' | 'unisex' | 'kids') | null;
  /**
   * Ольфакторное семейство.
   */
  family?: ('floral' | 'woody' | 'oriental' | 'fresh' | 'fougere' | 'chypre') | null;
  /**
   * Раздел каталога (не «Кому») — влияет на левую навигацию.
   */
  productCategory: 'perfume' | 'bodyCare';
  /**
   * Страна-производитель — фасет каталога.
   */
  countryOfOrigin: 'uae' | 'europe' | 'usa';
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Первая картинка — обложка карточки.
   */
  images?: (number | Media)[] | null;
  /**
   * Объём, цена и остаток. Общие для всех локалей.
   */
  variants: {
    /**
     * мл
     */
    volume: number;
    sku: string;
    /**
     * MDL
     */
    price: number;
    /**
     * MDL, до скидки
     */
    oldPrice?: number | null;
    stock: number;
    /**
     * Показывать вариант на витрине.
     */
    isActive?: boolean | null;
    id?: string | null;
  }[];
  /**
   * Плоский список — по нему работают фильтры и карточка.
   */
  notes?: (number | Note)[] | null;
  /**
   * Необязательно. Для страницы товара.
   */
  pyramid?: {
    top?: (number | Note)[] | null;
    heart?: (number | Note)[] | null;
    base?: (number | Note)[] | null;
  };
  /**
   * Ключ строки прайса клиента. По нему идёт upsert при импорте.
   */
  handle: string;
  /**
   * Латиницей, один на все локали. Пусто — соберётся из названия.
   */
  slug: string;
  isNew?: boolean | null;
  isHit?: boolean | null;
  minPrice?: number | null;
  maxPrice?: number | null;
  inStock?: boolean | null;
  /**
   * Есть активный вариант с oldPrice > price.
   */
  hasDiscount?: boolean | null;
  /**
   * Максимальный % скидки среди активных вариантов.
   */
  maxDiscountPercent?: number | null;
  seo?: {
    /**
     * До ~60 знаков. Пусто — берётся название.
     */
    title?: string | null;
    /**
     * До ~160 знаков.
     */
    description?: string | null;
    /**
     * Картинка для OG-превью.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: number;
  title: string;
  /**
   * Латиницей, один на все локали. Пусто — соберётся из названия.
   */
  slug: string;
  description?: string | null;
  logo?: (number | null) | Media;
  /**
   * Страна бренда — для страницы бренда.
   */
  country?: string | null;
  /**
   * Показывать в бренд-строке на главной.
   */
  isFeatured?: boolean | null;
  seo?: {
    /**
     * До ~60 знаков. Пусто — берётся название.
     */
    title?: string | null;
    /**
     * До ~160 знаков.
     */
    description?: string | null;
    /**
     * Картинка для OG-превью.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Альтернативный текст — локализуется.
   */
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    full?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * Латиницей, один на все локали. Пусто — соберётся из названия.
   */
  slug: string;
  description?: string | null;
  /**
   * Родительская категория (вложенность).
   */
  parent?: (number | null) | Category;
  /**
   * Картинка плитки в ленте категорий на главной.
   */
  image?: (number | null) | Media;
  /**
   * Порядок вывода, по возрастанию.
   */
  order?: number | null;
  seo?: {
    /**
     * До ~60 знаков. Пусто — берётся название.
     */
    title?: string | null;
    /**
     * До ~160 знаков.
     */
    description?: string | null;
    /**
     * Картинка для OG-превью.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notes".
 */
export interface Note {
  id: number;
  title: string;
  /**
   * Латиницей, один на все локали. Пусто — соберётся из названия.
   */
  slug: string;
  description?: string | null;
  /**
   * Группа ноты — для навигации по нотам.
   */
  group?: ('citrus' | 'floral' | 'woody' | 'spicy' | 'sweet' | 'fresh' | 'animalic') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gift-items".
 */
export interface GiftItem {
  id: number;
  title: string;
  /**
   * Латиницей, один на все локали. Пусто — соберётся из названия.
   */
  slug: string;
  /**
   * Раздел витрины: «Подарочные сертификаты» или «Gift box».
   */
  type: 'certificate' | 'giftBox';
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (number | null) | Media;
  /**
   * Тот же механизм, что у вариантов товара — сумма в MDL вместо объёма.
   */
  variants: {
    /**
     * Номинал, MDL
     */
    amount: number;
    sku: string;
    stock: number;
    /**
     * Показывать номинал на витрине.
     */
    isActive?: boolean | null;
    id?: string | null;
  }[];
  /**
   * Показывать товар на витрине.
   */
  isActive?: boolean | null;
  minPrice?: number | null;
  maxPrice?: number | null;
  inStock?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Латиницей, один на все локали. Пусто — соберётся из названия.
   */
  slug: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  seo?: {
    /**
     * До ~60 знаков. Пусто — берётся название.
     */
    title?: string | null;
    /**
     * До ~160 знаков.
     */
    description?: string | null;
    /**
     * Картинка для OG-превью.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  orderNumber?: string | null;
  /**
   * Токен страницы статуса заказа.
   */
  statusToken?: string | null;
  status: 'new' | 'confirmed' | 'ready' | 'issued' | 'cancelled';
  /**
   * Без звонка = клиент просил не звонить. Телефон обязателен в обоих случаях.
   */
  checkoutMode: 'standard' | 'noCall';
  /**
   * Локаль, с которой пришла заявка.
   */
  locale?: ('ro' | 'ru' | 'en') | null;
  /**
   * cart / one-click / site
   */
  source?: string | null;
  customer: {
    name: string;
    phone: string;
    /**
     * Необязательно — для письма-подтверждения и ссылки на статус заказа.
     */
    email?: string | null;
    /**
     * Необязательно — адрес доставки или выдачи.
     */
    address?: string | null;
    messenger?: ('telegram' | 'viber' | 'whatsapp' | 'call') | null;
  };
  comment?: string | null;
  /**
   * Снапшот на момент заявки — не меняется вслед за каталогом.
   */
  items?:
    | {
        /**
         * Ссылка на товар, если он ещё существует.
         */
        product?: (number | null) | Product;
        title: string;
        brandTitle?: string | null;
        sku: string;
        /**
         * мл
         */
        volume?: number | null;
        /**
         * MDL
         */
        price: number;
        qty: number;
        lineTotal: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Итог заявки, MDL.
   */
  total: number;
  /**
   * CSV заявки для Excel (UTF-8 с BOM, разделитель «;»).
   */
  exportCsv?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * Менеджер: товары только на чтение, заказы — полностью.
   */
  role: 'admin' | 'manager';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'brands';
        value: number | Brand;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'notes';
        value: number | Note;
      } | null)
    | ({
        relationTo: 'gift-items';
        value: number | GiftItem;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  brand?: T;
  categories?: T;
  gender?: T;
  family?: T;
  productCategory?: T;
  countryOfOrigin?: T;
  description?: T;
  images?: T;
  variants?:
    | T
    | {
        volume?: T;
        sku?: T;
        price?: T;
        oldPrice?: T;
        stock?: T;
        isActive?: T;
        id?: T;
      };
  notes?: T;
  pyramid?:
    | T
    | {
        top?: T;
        heart?: T;
        base?: T;
      };
  handle?: T;
  slug?: T;
  isNew?: T;
  isHit?: T;
  minPrice?: T;
  maxPrice?: T;
  inStock?: T;
  hasDiscount?: T;
  maxDiscountPercent?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  logo?: T;
  country?: T;
  isFeatured?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  parent?: T;
  image?: T;
  order?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notes_select".
 */
export interface NotesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  group?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gift-items_select".
 */
export interface GiftItemsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  type?: T;
  description?: T;
  image?: T;
  variants?:
    | T
    | {
        amount?: T;
        sku?: T;
        stock?: T;
        isActive?: T;
        id?: T;
      };
  isActive?: T;
  minPrice?: T;
  maxPrice?: T;
  inStock?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  body?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        full?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  statusToken?: T;
  status?: T;
  checkoutMode?: T;
  locale?: T;
  source?: T;
  customer?:
    | T
    | {
        name?: T;
        phone?: T;
        email?: T;
        address?: T;
        messenger?: T;
      };
  comment?: T;
  items?:
    | T
    | {
        product?: T;
        title?: T;
        brandTitle?: T;
        sku?: T;
        volume?: T;
        price?: T;
        qty?: T;
        lineTotal?: T;
        id?: T;
      };
  total?: T;
  exportCsv?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  hero: {
    /**
     * Фирменная EN-фраза — не переводится.
     */
    eyebrow?: string | null;
    /**
     * Фирменные EN-фразы оставляйте на английском.
     */
    title: string;
    subtitle?: string | null;
    ctaLabel?: string | null;
    /**
     * Без префикса локали.
     */
    ctaHref?: string | null;
  };
  /**
   * Пока включена и дата попадает в интервал — заменяет hero целиком. Один экран, без слайдера.
   */
  promoHero?: {
    enabled?: boolean | null;
    /**
     * Пусто — берётся обычный «Perfumes for everyone».
     */
    eyebrow?: string | null;
    title?: string | null;
    subtitle?: string | null;
    /**
     * Пусто — берётся подпись выбранной цели.
     */
    ctaLabel?: string | null;
    ctaTargetMode?: ('system' | 'page') | null;
    /**
     * Каталог, Бренды, Главная и т.п. — не Pages-контент.
     */
    ctaTarget?: ('home' | 'catalog' | 'catalogDiscounted' | 'catalogNew' | 'brands' | 'orderLookup') | null;
    /**
     * О нас, Доставка, Контакты и другой контент из коллекции Страницы.
     */
    ctaTargetPage?: (number | null) | Page;
    /**
     * Заполнено — используется вместо выбора выше (внешний URL или внутренний путь без префикса локали, напр. /catalog).
     */
    ctaTargetOverride?: string | null;
    /**
     * Необязательно. Пусто — фон остаётся navy.
     */
    image?: (number | null) | Media;
    /**
     * Пусто — без ограничения снизу.
     */
    startDate?: string | null;
    /**
     * Пусто — без ограничения сверху.
     */
    endDate?: string | null;
  };
  /**
   * Четыре плитки; счётчики товаров считаются из БД.
   */
  categoryTiles?:
    | {
        category: number | Category;
        /**
         * Пусто — берётся название категории.
         */
        labelOverride?: string | null;
        id?: string | null;
      }[]
    | null;
  newRow?: {
    title?: string | null;
    linkLabel?: string | null;
    limit?: number | null;
  };
  /**
   * WIREFRAMES.md §Опциональный слот — по умолчанию выключен.
   */
  hitsRow?: {
    enabled?: boolean | null;
    title?: string | null;
    linkLabel?: string | null;
    limit?: number | null;
  };
  editorial?: {
    /**
     * Фирменная EN-фраза — не переводится.
     */
    phrase?: string | null;
    text?: string | null;
    linkLabel?: string | null;
    linkHref?: string | null;
    /**
     * Пусто — на плите cream остаётся знак бренда.
     */
    image?: (number | null) | Media;
  };
  /**
   * Одна центрированная строка названий без логотипов.
   */
  featuredBrands?: (number | Brand)[] | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  /**
   * Название бренда — не переводится (BRAND.md §7).
   */
  siteName?: string | null;
  /**
   * Дескриптор логотипа — фирменная EN-фраза, не переводится.
   */
  tagline?: string | null;
  contacts?: {
    phone?: string | null;
    email?: string | null;
    address?: string | null;
    workingHours?: string | null;
    /**
     * Ссылка на карту.
     */
    mapUrl?: string | null;
  };
  messengers?: {
    telegram?: string | null;
    viber?: string | null;
    whatsapp?: string | null;
  };
  social?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Строка под логотипом в футере.
   */
  footerNote?: string | null;
  /**
   * Полоса над шапкой на всех страницах, если включена и дата подходит.
   */
  promoBanner?: {
    enabled?: boolean | null;
    /**
     * Текст полосы.
     */
    text?: string | null;
    /**
     * Пусто — берётся подпись выбранной цели.
     */
    linkLabel?: string | null;
    linkTargetMode?: ('system' | 'page') | null;
    /**
     * Каталог, Бренды, Главная и т.п. — не Pages-контент.
     */
    linkTarget?: ('home' | 'catalog' | 'catalogDiscounted' | 'catalogNew' | 'brands' | 'orderLookup') | null;
    /**
     * О нас, Доставка, Контакты и другой контент из коллекции Страницы.
     */
    linkTargetPage?: (number | null) | Page;
    /**
     * Заполнено — используется вместо выбора выше (внешний URL или внутренний путь без префикса локали, напр. /catalog).
     */
    linkTargetOverride?: string | null;
    /**
     * Пусто — без ограничения снизу.
     */
    startDate?: string | null;
    /**
     * Пусто — без ограничения сверху.
     */
    endDate?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  /**
   * Каталог · Бренды · Новинки · О нас (WIREFRAMES.md §Шапка).
   */
  header?:
    | {
        label: string;
        targetMode?: ('system' | 'page') | null;
        /**
         * Каталог, Бренды, Главная и т.п. — не Pages-контент.
         */
        target?: ('home' | 'catalog' | 'catalogDiscounted' | 'catalogNew' | 'brands' | 'orderLookup') | null;
        /**
         * О нас, Доставка, Контакты и другой контент из коллекции Страницы.
         */
        targetPage?: (number | null) | Page;
        /**
         * Заполнено — используется вместо выбора выше (внешний URL или внутренний путь без префикса локали, напр. /catalog).
         */
        targetOverride?: string | null;
        id?: string | null;
      }[]
    | null;
  footerColumns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        subtitle?: T;
        ctaLabel?: T;
        ctaHref?: T;
      };
  promoHero?:
    | T
    | {
        enabled?: T;
        eyebrow?: T;
        title?: T;
        subtitle?: T;
        ctaLabel?: T;
        ctaTargetMode?: T;
        ctaTarget?: T;
        ctaTargetPage?: T;
        ctaTargetOverride?: T;
        image?: T;
        startDate?: T;
        endDate?: T;
      };
  categoryTiles?:
    | T
    | {
        category?: T;
        labelOverride?: T;
        id?: T;
      };
  newRow?:
    | T
    | {
        title?: T;
        linkLabel?: T;
        limit?: T;
      };
  hitsRow?:
    | T
    | {
        enabled?: T;
        title?: T;
        linkLabel?: T;
        limit?: T;
      };
  editorial?:
    | T
    | {
        phrase?: T;
        text?: T;
        linkLabel?: T;
        linkHref?: T;
        image?: T;
      };
  featuredBrands?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  contacts?:
    | T
    | {
        phone?: T;
        email?: T;
        address?: T;
        workingHours?: T;
        mapUrl?: T;
      };
  messengers?:
    | T
    | {
        telegram?: T;
        viber?: T;
        whatsapp?: T;
      };
  social?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  footerNote?: T;
  promoBanner?:
    | T
    | {
        enabled?: T;
        text?: T;
        linkLabel?: T;
        linkTargetMode?: T;
        linkTarget?: T;
        linkTargetPage?: T;
        linkTargetOverride?: T;
        startDate?: T;
        endDate?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  header?:
    | T
    | {
        label?: T;
        targetMode?: T;
        target?: T;
        targetPage?: T;
        targetOverride?: T;
        id?: T;
      };
  footerColumns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}